### ISSUE TITLE
Extra configuration for TS35-E3

### ISSUE THREAD

**Issue by achenakid** [willngton/3DPrinterConfig#1]
Had some trouble configuring TS35-E3. The touch feedback direction is always wrong, until did below modifications

sudo nano /usr/share/X11/xorg.conf.d/40-libinput.conf

find Identifier "libinput touchscreen catchall" as below,

Section "InputClass"
        Identifier "libinput touchscreen catchall"
        MatchIsTouchscreen "on"
        MatchDevicePath "/dev/input/event*"
        Driver "libinput"
EndSection

Add one line Option "TransformationMatrix" "0 -1 1 1 0 0 0 0 1" as below,

Section "InputClass"
        Identifier "libinput touchscreen catchall"
        MatchIsTouchscreen "on"
        Option "TransformationMatrix" "0 -1 1 1 0 0 0 0 1"
        MatchDevicePath "/dev/input/event*"
        Driver "libinput"
EndSection

save and reboot

**Comment by willngton** [comment]
> 
Thank you very much for the help mate, was scratching my head trying to find a long term solution's for touch configuration.

I will test this out and update the guide, 

Thank you again !

**Comment by willngton** [comment]
I have update guide, and no more need to try and error
