### ISSUE TITLE
Work it with TS35-E3 , too? ...

### ISSUE THREAD

**Issue by derTimm0** [willngton/3DPrinterConfig#2]
...in best case with a Orange Pi PC? (AFAIK little bit other PIO Pinout)
For Testing ,it run at the Moment Klipper/Fluidd on it.

**Comment by willngton** [comment]
> ...in best case with a Orange Pi PC? (AFAIK little bit other PIO Pinout) For Testing ,it run at the Moment Klipper/Fluidd on it.

Hello.

Yes, it should work with no problem, considering you are using an raspberry pi, I cant validade for orangepi.
